2020-12-27 14:24:14,636 - print_in_log.py[line:36] - INFO: 
 Exploring complete.
2020-12-27 14:24:14,644 - print_in_log.py[line:36] - INFO: 
 Data preprocessing complete.
2020-12-27 14:24:15,661 - print_in_log.py[line:39] - ERROR: 
 Traceback (most recent call last):
  File "<ipython-input-3-c40b8c7a74a6>", line 55, in <module>
    selector, selected_data = Selector(df).filter(data.target, k = 30, method = 'IV')
  File "D:\troywu666\business_stuff\民生对公项目\模型标准化\feature_selection.py", line 73, in filter
    selector = SelectKBest(IV, k = k).fit(self.fea, y)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py", line 344, in fit
    multi_output=True)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py", line 433, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 821, in check_X_y
    estimator=estimator)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 664, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "E:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

2020-12-27 14:25:14,993 - print_in_log.py[line:36] - INFO: 
 Model training complete.
2020-12-27 14:25:21,202 - print_in_log.py[line:36] - INFO: 
 Evaluation complete.
2020-12-27 14:34:00,739 - print_in_log.py[line:36] - INFO: 
 训练集的用户个数有212062
2020-12-27 14:34:00,744 - print_in_log.py[line:36] - INFO: 
 训练集的商户个数有1993
2020-12-27 14:34:00,767 - print_in_log.py[line:36] - INFO: 
 测试集的用户个数有212108
2020-12-27 14:34:00,772 - print_in_log.py[line:36] - INFO: 
 测试集的商户个数有1993
2020-12-27 14:34:01,207 - print_in_log.py[line:36] - INFO: 
 日志数据的用户个数有424170
2020-12-27 14:34:01,730 - print_in_log.py[line:36] - INFO: 
 日志数据的商户个数有4995
2020-12-27 14:34:02,201 - print_in_log.py[line:36] - INFO: 
 日志数据的商品种类数有1658
2020-12-27 14:34:03,061 - print_in_log.py[line:36] - INFO: 
 日志数据的品牌个数有4123
2020-12-27 14:34:03,088 - print_in_log.py[line:36] - INFO: 
 个人数据的用户个数有424170
2020-12-27 14:34:03,204 - print_in_log.py[line:36] - INFO: 
 训练集和测试集的用户重叠数为0
2020-12-27 14:34:03,274 - print_in_log.py[line:36] - INFO: 
 训练集和测试集的商户重叠数为1992
2020-12-27 14:36:21,611 - print_in_log.py[line:36] - INFO: 
 Transform path feature sucessful.
2020-12-27 14:36:22,350 - print_in_log.py[line:36] - INFO: 
 Count feature complete.
2020-12-27 14:36:22,423 - print_in_log.py[line:36] - INFO: 
 Unique feature complete.
2020-12-27 14:36:22,540 - print_in_log.py[line:36] - INFO: 
 Freq feature complete.
2020-12-27 14:36:22,654 - print_in_log.py[line:36] - INFO: 
 Freq_cnt feature complete.
2020-12-27 14:36:26,075 - print_in_log.py[line:36] - INFO: 
 Merchant group by action feature complete.
2020-12-27 14:36:29,827 - print_in_log.py[line:36] - INFO: 
 Merchant_cat group by action feature complete.
2020-12-27 14:36:32,119 - print_in_log.py[line:36] - INFO: 
 Statistic feature complete.
2020-12-27 14:36:33,123 - print_in_log.py[line:36] - INFO: 
 Vectorizer complete.
2020-12-27 14:36:33,139 - word2vec.py[line:1588] - INFO: 
 collecting all words and their counts
2020-12-27 14:36:33,141 - word2vec.py[line:1573] - INFO: 
 PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2020-12-27 14:36:33,169 - word2vec.py[line:1596] - INFO: 
 collected 4395 word types from a corpus of 149924 raw words and 1000 sentences
2020-12-27 14:36:33,173 - word2vec.py[line:1647] - INFO: 
 Loading a fresh vocabulary
2020-12-27 14:36:33,183 - word2vec.py[line:1671] - INFO: 
 effective_min_count=5 retains 3152 unique words (71% of original 4395, drops 1243)
2020-12-27 14:36:33,185 - word2vec.py[line:1677] - INFO: 
 effective_min_count=5 leaves 147038 word corpus (98% of original 149924, drops 2886)
2020-12-27 14:36:33,199 - word2vec.py[line:1736] - INFO: 
 deleting the raw counts dictionary of 4395 items
2020-12-27 14:36:33,202 - word2vec.py[line:1739] - INFO: 
 sample=0.001 downsamples 44 most-common words
2020-12-27 14:36:33,206 - word2vec.py[line:1742] - INFO: 
 downsampling leaves estimated 135513 word corpus (92.2% of prior 147038)
2020-12-27 14:36:34,803 - base_any2vec.py[line:1022] - INFO: 
 estimated required memory for 3152 words and 100 dimensions: 4097600 bytes
2020-12-27 14:36:34,841 - word2vec.py[line:1888] - INFO: 
 resetting layer weights
2020-12-27 14:36:35,542 - base_any2vec.py[line:1210] - INFO: 
 training model with 4 workers on 3152 vocabulary and 100 features, using sg=0 hs=0 sample=0.001 negative=5 window=5
2020-12-27 14:36:35,711 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 3 more threads
2020-12-27 14:36:35,715 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 2 more threads
2020-12-27 14:36:35,719 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 1 more threads
2020-12-27 14:36:35,721 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 0 more threads
2020-12-27 14:36:35,723 - base_any2vec.py[line:1346] - INFO: 
 EPOCH - 1 : training on 149924 raw words (135590 effective words) took 0.2s, 771748 effective words/s
2020-12-27 14:36:35,810 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 3 more threads
2020-12-27 14:36:35,818 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 2 more threads
2020-12-27 14:36:35,821 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 1 more threads
2020-12-27 14:36:35,826 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 0 more threads
2020-12-27 14:36:35,828 - base_any2vec.py[line:1346] - INFO: 
 EPOCH - 2 : training on 149924 raw words (135603 effective words) took 0.1s, 1387124 effective words/s
2020-12-27 14:36:35,919 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 3 more threads
2020-12-27 14:36:35,926 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 2 more threads
2020-12-27 14:36:35,928 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 1 more threads
2020-12-27 14:36:35,932 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 0 more threads
2020-12-27 14:36:35,933 - base_any2vec.py[line:1346] - INFO: 
 EPOCH - 3 : training on 149924 raw words (135541 effective words) took 0.1s, 1349397 effective words/s
2020-12-27 14:36:36,016 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 3 more threads
2020-12-27 14:36:36,022 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 2 more threads
2020-12-27 14:36:36,025 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 1 more threads
2020-12-27 14:36:36,027 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 0 more threads
2020-12-27 14:36:36,029 - base_any2vec.py[line:1346] - INFO: 
 EPOCH - 4 : training on 149924 raw words (135503 effective words) took 0.1s, 1510087 effective words/s
2020-12-27 14:36:36,115 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 3 more threads
2020-12-27 14:36:36,122 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 2 more threads
2020-12-27 14:36:36,128 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 1 more threads
2020-12-27 14:36:36,130 - base_any2vec.py[line:349] - INFO: 
 worker thread finished; awaiting finish of 0 more threads
2020-12-27 14:36:36,132 - base_any2vec.py[line:1346] - INFO: 
 EPOCH - 5 : training on 149924 raw words (135445 effective words) took 0.1s, 1403881 effective words/s
2020-12-27 14:36:36,141 - base_any2vec.py[line:1382] - INFO: 
 training on a 749620 raw words (677682 effective words) took 0.6s, 1134400 effective words/s
2020-12-27 14:36:36,758 - print_in_log.py[line:36] - INFO: 
 Word2Vec embeddings complete.
2020-12-27 14:36:36,980 - print_in_log.py[line:39] - ERROR: 
 TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<ipython-input-7-da43413533f6>", line 354, in <module>
    model_train, model_test, model_name = model(x_train.values, y_train, x_test.values)
  File "<ipython-input-7-da43413533f6>", line 337, in xgb_clf
    xgb_train, xgb_test = stacking_featurizer(xgb, X_train, y_train, X_valid, 'xgb', label_split)
  File "<ipython-input-7-da43413533f6>", line 283, in stacking_featurizer
    train_matrix = model.DMatrix(tr_x, label = tr_y, missing = -1)
  File "E:\ProgramData\Anaconda3\lib\site-packages\xgboost\core.py", line 473, in __init__
    self._init_from_npy2d(data, missing, nthread)
  File "E:\ProgramData\Anaconda3\lib\site-packages\xgboost\core.py", line 549, in _init_from_npy2d
    data = np.array(mat.reshape(mat.size), copy=False, dtype=np.float32)
ValueError: setting an array element with a sequence.

a3\lib\site-packages\xgboost\core.py", line 473, in __init__
    self._init_from_npy2d(data, missing, nthread)
  File "E:\ProgramData\Anaconda3\lib\site-packages\xgboost\core.py", line 549, in _init_from_npy2d
    data = np.array(mat.reshape(mat.size), copy=False, dtype=np.float32)
ValueError: setting an array element with a sequence.

